// 公司治理文书类模板定义
export const 公司治理文书模板 = {
  '公司章程.docx': {
    title: '公司章程',
    category: '公司治理文书',
    description: '有限责任公司或股份有限公司的章程文件',
    scene: '公司设立、章程修改',
    sections: [
      { type: 'paragraph', content: '{{公司名称}}公司章程', indent: false, style: 'center' },
      { type: 'empty' },
      {
        type: 'paragraph',
        content: '根据《中华人民共和国公司法》及相关法律法规的规定，特制定本章程。'
      },
      { type: 'empty' },
      { type: 'heading', content: '第一章 总则' },
      { type: 'paragraph', content: '第一条 公司名称：{{公司名称}}' },
      { type: 'paragraph', content: '第二条 公司住所：{{公司住所}}' },
      { type: 'paragraph', content: '第三条 公司类型：{{公司类型}}（有限责任公司/股份有限公司）' },
      { type: 'paragraph', content: '第四条 公司经营范围：{{经营范围}}' },
      { type: 'paragraph', content: '第五条 公司注册资本：人民币{{注册资本}}元' },
      { type: 'paragraph', content: '第六条 公司营业期限：{{营业期限}}（自{{成立日期}}起至{{终止日期}}止，或长期）' },
      { type: 'empty' },
      { type: 'heading', content: '第二章 股东' },
      { type: 'paragraph', content: '第七条 公司股东及其出资情况：' },
      { type: 'paragraph', content: '1. {{股东1名称}}：认缴出资{{认缴出资}}元，占注册资本{{比例}}%，实缴出资{{实缴出资}}元；' },
      { type: 'paragraph', content: '2. {{股东2名称}}：认缴出资{{认缴出资}}元，占注册资本{{比例}}%，实缴出资{{实缴出资}}元；' },
      { type: 'paragraph', content: '3. {{股东3名称}}：认缴出资{{认缴出资}}元，占注册资本{{比例}}%，实缴出资{{实缴出资}}元。' },
      { type: 'paragraph', content: '第八条 股东的权利：' },
      { type: 'paragraph', content: '（一）参加或委派代表参加股东会，并行使表决权；' },
      { type: 'paragraph', content: '（二）选举和被选举为董事、监事；' },
      { type: 'paragraph', content: '（三）查阅、复制公司章程、股东会会议记录、董事会会议决议、监事会会议决议和财务会计报告；' },
      { type: 'paragraph', content: '（四）按照出资比例分取红利；' },
      { type: 'paragraph', content: '（五）优先购买其他股东转让的出资；' },
      { type: 'paragraph', content: '（六）公司新增资本时，优先认缴出资；' },
      { type: 'paragraph', content: '（七）公司终止后，依法分得公司的剩余财产；' },
      { type: 'paragraph', content: '（八）法律、行政法规及本章程规定的其他权利。' },
      { type: 'paragraph', content: '第九条 股东的义务：' },
      { type: 'paragraph', content: '（一）按期足额缴纳出资；' },
      { type: 'paragraph', content: '（二）遵守公司章程；' },
      { type: 'paragraph', content: '（三）不得滥用股东权利损害公司或者其他股东的利益；' },
      { type: 'paragraph', content: '（四）不得滥用公司法人独立地位和股东有限责任损害公司债权人的利益；' },
      { type: 'paragraph', content: '（五）法律、行政法规及本章程规定的其他义务。' },
      { type: 'empty' },
      { type: 'heading', content: '第三章 股东会' },
      { type: 'paragraph', content: '第十条 股东会由全体股东组成，是公司的权力机构。' },
      { type: 'paragraph', content: '第十一条 股东会行使下列职权：' },
      { type: 'paragraph', content: '（一）决定公司的经营方针和投资计划；' },
      { type: 'paragraph', content: '（二）选举和更换非由职工代表担任的董事、监事，决定有关董事、监事的报酬事项；' },
      { type: 'paragraph', content: '（三）审议批准董事会的报告；' },
      { type: 'paragraph', content: '（四）审议批准监事会或者监事的报告；' },
      { type: 'paragraph', content: '（五）审议批准公司的年度财务预算方案、决算方案；' },
      { type: 'paragraph', content: '（六）审议批准公司的利润分配方案和弥补亏损方案；' },
      { type: 'paragraph', content: '（七）对公司增加或者减少注册资本作出决议；' },
      { type: 'paragraph', content: '（八）对发行公司债券作出决议；' },
      { type: 'paragraph', content: '（九）对公司合并、分立、解散、清算或者变更公司形式作出决议；' },
      { type: 'paragraph', content: '（十）修改公司章程；' },
      { type: 'paragraph', content: '（十一）公司章程规定的其他职权。' },
      { type: 'paragraph', content: '第十二条 股东会会议分为定期会议和临时会议。定期会议每年召开{{次数}}次。' },
      { type: 'paragraph', content: '第十三条 股东会会议由股东按照出资比例行使表决权。股东会会议作出修改公司章程、增加或者减少注册资本的决议，以及公司合并、分立、解散或者变更公司形式的决议，必须经代表三分之二以上表决权的股东通过。' },
      { type: 'empty' },
      { type: 'heading', content: '第四章 董事会' },
      { type: 'paragraph', content: '第十四条 公司设董事会，成员为{{人数}}人，由股东会选举产生。' },
      { type: 'paragraph', content: '第十五条 董事会设董事长一人，由董事会选举产生。' },
      { type: 'paragraph', content: '第十六条 董事任期{{任期}}年，任期届满，可以连选连任。' },
      { type: 'paragraph', content: '第十七条 董事会行使下列职权：' },
      { type: 'paragraph', content: '（一）召集股东会会议，并向股东会报告工作；' },
      { type: 'paragraph', content: '（二）执行股东会的决议；' },
      { type: 'paragraph', content: '（三）决定公司的经营计划和投资方案；' },
      { type: 'paragraph', content: '（四）制订公司的年度财务预算方案、决算方案；' },
      { type: 'paragraph', content: '（五）制订公司的利润分配方案和弥补亏损方案；' },
      { type: 'paragraph', content: '（六）制订公司增加或者减少注册资本以及发行公司债券的方案；' },
      { type: 'paragraph', content: '（七）制订公司合并、分立、解散或者变更公司形式的方案；' },
      { type: 'paragraph', content: '（八）决定公司内部管理机构的设置；' },
      { type: 'paragraph', content: '（九）决定聘任或者解聘公司经理及其报酬事项，并根据经理的提名决定聘任或者解聘公司副经理、财务负责人及其报酬事项；' },
      { type: 'paragraph', content: '（十）制定公司的基本管理制度；' },
      { type: 'paragraph', content: '（十一）公司章程规定的其他职权。' },
      { type: 'empty' },
      { type: 'heading', content: '第五章 监事会' },
      { type: 'paragraph', content: '第十八条 公司设监事会，成员为{{人数}}人，由股东会选举产生。' },
      { type: 'paragraph', content: '第十九条 监事会设主席一人，由全体监事过半数选举产生。' },
      { type: 'paragraph', content: '第二十条 监事的任期每届为{{任期}}年，任期届满，可以连选连任。' },
      { type: 'paragraph', content: '第二十一条 监事会行使下列职权：' },
      { type: 'paragraph', content: '（一）检查公司财务；' },
      { type: 'paragraph', content: '（二）对董事、高级管理人员执行公司职务的行为进行监督，对违反法律、行政法规、公司章程或者股东会决议的董事、高级管理人员提出罢免的建议；' },
      { type: 'paragraph', content: '（三）当董事、高级管理人员的行为损害公司的利益时，要求董事、高级管理人员予以纠正；' },
      { type: 'paragraph', content: '（四）提议召开临时股东会会议，在董事会不履行本法规定的召集和主持股东会会议职责时召集和主持股东会会议；' },
      { type: 'paragraph', content: '（五）向股东会会议提出提案；' },
      { type: 'paragraph', content: '（六）依照《公司法》第一百五十一条的规定，对董事、高级管理人员提起诉讼；' },
      { type: 'paragraph', content: '（七）公司章程规定的其他职权。' },
      { type: 'empty' },
      { type: 'heading', content: '第六章 公司财务、会计' },
      { type: 'paragraph', content: '第二十二条 公司应当依照法律、行政法规和国务院财政部门的规定建立本公司的财务、会计制度。' },
      { type: 'paragraph', content: '第二十三条 公司应当在每一会计年度终了时编制财务会计报告，并依法经会计师事务所审计。' },
      { type: 'paragraph', content: '第二十四条 公司分配当年税后利润时，应当提取利润的百分之十列入公司法定公积金。公司法定公积金累计额为公司注册资本的百分之五十以上的，可以不再提取。' },
      { type: 'empty' },
      { type: 'heading', content: '第七章 合并、分立、增资、减资' },
      { type: 'paragraph', content: '第二十五条 公司合并、分立、增资、减资，应当由股东会作出决议，并依法办理相关手续。' },
      { type: 'empty' },
      { type: 'heading', content: '第八章 解散和清算' },
      { type: 'paragraph', content: '第二十六条 公司因下列原因解散：' },
      { type: 'paragraph', content: '（一）公司章程规定的营业期限届满或者公司章程规定的其他解散事由出现；' },
      { type: 'paragraph', content: '（二）股东会决议解散；' },
      { type: 'paragraph', content: '（三）因公司合并或者分立需要解散；' },
      { type: 'paragraph', content: '（四）依法被吊销营业执照、责令关闭或者被撤销；' },
      { type: 'paragraph', content: '（五）人民法院依照《公司法》第一百八十二条的规定予以解散。' },
      { type: 'paragraph', content: '第二十七条 公司解散，应当依法成立清算组进行清算。' },
      { type: 'empty' },
      { type: 'heading', content: '第九章 附则' },
      { type: 'paragraph', content: '第二十八条 本章程自公司成立之日起生效。' },
      { type: 'paragraph', content: '第二十九条 本章程的修改，应当由股东会作出决议，并依法办理变更登记。' },
      { type: 'paragraph', content: '第三十条 本章程未尽事宜，依照《公司法》及相关法律法规的规定执行。' },
      { type: 'empty' },
      { type: 'paragraph', content: '全体股东签字（盖章）：', indent: false },
      { type: 'empty' },
      { type: 'paragraph', content: '{{股东1名称}}（签字/盖章）', indent: false },
      { type: 'paragraph', content: '{{股东2名称}}（签字/盖章）', indent: false },
      { type: 'paragraph', content: '{{股东3名称}}（签字/盖章）', indent: false },
      { type: 'empty' },
      { type: 'paragraph', content: '{{日期}}', indent: false }
    ]
  },

  '股东协议.docx': {
    title: '股东协议',
    category: '公司治理文书',
    description: '公司股东之间就公司治理、股权转让等事项达成的协议',
    scene: '公司设立、股权调整',
    sections: [
      { type: 'paragraph', content: '股东协议', indent: false, style: 'center' },
      { type: 'empty' },
      {
        type: 'paragraph',
        content: '本协议由以下各方于{{日期}}在{{签订地点}}签署：'
      },
      { type: 'empty' },
      { type: 'paragraph', content: '甲方（股东1）：{{股东1名称}}', indent: false },
      { type: 'paragraph', content: '身份证号/统一社会信用代码：{{股东1证件号}}', indent: false },
      { type: 'paragraph', content: '地址：{{股东1地址}}', indent: false },
      { type: 'paragraph', content: '联系电话：{{股东1电话}}', indent: false },
      { type: 'empty' },
      { type: 'paragraph', content: '乙方（股东2）：{{股东2名称}}', indent: false },
      { type: 'paragraph', content: '身份证号/统一社会信用代码：{{股东2证件号}}', indent: false },
      { type: 'paragraph', content: '地址：{{股东2地址}}', indent: false },
      { type: 'paragraph', content: '联系电话：{{股东2电话}}', indent: false },
      { type: 'empty' },
      { type: 'paragraph', content: '丙方（股东3）：{{股东3名称}}', indent: false },
      { type: 'paragraph', content: '身份证号/统一社会信用代码：{{股东3证件号}}', indent: false },
      { type: 'paragraph', content: '地址：{{股东3地址}}', indent: false },
      { type: 'paragraph', content: '联系电话：{{股东3电话}}', indent: false },
      { type: 'empty' },
      {
        type: 'paragraph',
        content: '鉴于：'
      },
      { type: 'paragraph', content: '1. 各方拟共同设立{{公司名称}}（以下简称"公司"）；' },
      { type: 'paragraph', content: '2. 各方就公司的治理、股权转让、利润分配等事项达成一致意见；' },
      { type: 'paragraph', content: '3. 各方同意按照本协议的约定行使股东权利、履行股东义务。' },
      { type: 'empty' },
      {
        type: 'paragraph',
        content: '经各方协商一致，就相关事宜达成如下协议：'
      },
      { type: 'empty' },
      { type: 'heading', content: '第一条 公司基本情况' },
      { type: 'paragraph', content: '1. 公司名称：{{公司名称}}' },
      { type: 'paragraph', content: '2. 公司住所：{{公司住所}}' },
      { type: 'paragraph', content: '3. 公司注册资本：人民币{{注册资本}}元' },
      { type: 'paragraph', content: '4. 公司经营范围：{{经营范围}}' },
      { type: 'empty' },
      { type: 'heading', content: '第二条 股权结构' },
      { type: 'paragraph', content: '1. 甲方认缴出资{{认缴出资}}元，占注册资本{{比例}}%，实缴出资{{实缴出资}}元；' },
      { type: 'paragraph', content: '2. 乙方认缴出资{{认缴出资}}元，占注册资本{{比例}}%，实缴出资{{实缴出资}}元；' },
      { type: 'paragraph', content: '3. 丙方认缴出资{{认缴出资}}元，占注册资本{{比例}}%，实缴出资{{实缴出资}}元。' },
      { type: 'empty' },
      { type: 'heading', content: '第三条 公司治理' },
      { type: 'paragraph', content: '1. 公司设董事会，成员为{{人数}}人，其中甲方委派{{人数}}人，乙方委派{{人数}}人，丙方委派{{人数}}人。' },
      { type: 'paragraph', content: '2. 公司设监事会，成员为{{人数}}人，其中甲方委派{{人数}}人，乙方委派{{人数}}人，丙方委派{{人数}}人。' },
      { type: 'paragraph', content: '3. 公司设总经理一人，由{{委派方}}委派。' },
      { type: 'paragraph', content: '4. 公司重大事项（包括但不限于增加或减少注册资本、合并、分立、解散、变更公司形式、修改公司章程等）需经全体股东一致同意。' },
      { type: 'empty' },
      { type: 'heading', content: '第四条 股权转让' },
      { type: 'paragraph', content: '1. 股东向股东以外的人转让股权，应当经其他股东过半数同意。' },
      { type: 'paragraph', content: '2. 其他股东在同等条件下享有优先购买权。' },
      { type: 'paragraph', content: '3. 股东之间可以相互转让其全部或者部分股权。' },
      { type: 'paragraph', content: '4. 股东不得向公司的竞争对手转让股权。' },
      { type: 'empty' },
      { type: 'heading', content: '第五条 利润分配' },
      { type: 'paragraph', content: '1. 公司分配当年税后利润时，应当提取利润的百分之十列入公司法定公积金。' },
      { type: 'paragraph', content: '2. 公司弥补亏损和提取公积金后所余税后利润，按照股东的出资比例分配。' },
      { type: 'paragraph', content: '3. 公司每年至少分配一次利润，具体分配方案由股东会决定。' },
      { type: 'empty' },
      { type: 'heading', content: '第六条 竞业限制' },
      { type: 'paragraph', content: '1. 股东在持有公司股权期间，不得从事与公司业务相同或相似的业务。' },
      { type: 'paragraph', content: '2. 股东不得利用公司的商业秘密、客户资源等为自己或他人谋取利益。' },
      { type: 'paragraph', content: '3. 股东违反本条约定的，应当赔偿公司因此遭受的全部损失。' },
      { type: 'empty' },
      { type: 'heading', content: '第七条 违约责任' },
      { type: 'paragraph', content: '1. 任何一方违反本协议约定的，应当承担违约责任，赔偿其他方因此遭受的全部损失。' },
      { type: 'paragraph', content: '2. 违约方应当支付违约金人民币{{违约金金额}}元。' },
      { type: 'empty' },
      { type: 'heading', content: '第八条 争议解决' },
      {
        type: 'paragraph',
        content: '本协议履行过程中发生争议的，由各方协商解决；协商不成的，依法向{{管辖法院}}人民法院起诉。'
      },
      { type: 'empty' },
      { type: 'heading', content: '第九条 其他约定' },
      { type: 'paragraph', content: '{{其他约定事项}}' },
      { type: 'empty' },
      {
        type: 'paragraph',
        content: '本协议一式{{份数}}份，各方各执一份，具有同等法律效力。自各方签字（盖章）之日起生效。'
      },
      { type: 'empty' },
      { type: 'paragraph', content: '甲方（签字/盖章）：{{股东1名称}}', indent: false },
      { type: 'paragraph', content: '乙方（签字/盖章）：{{股东2名称}}', indent: false },
      { type: 'paragraph', content: '丙方（签字/盖章）：{{股东3名称}}', indent: false },
      { type: 'empty' },
      { type: 'paragraph', content: '{{日期}}', indent: false }
    ]
  }
}

