// 劳动人事文书类模板定义
export const 劳动人事文书模板 = {
  '竞业限制协议.docx': {
    title: '竞业限制协议',
    category: '劳动人事文书',
    description: '用人单位与劳动者签订的竞业限制协议',
    scene: '员工离职、商业秘密保护',
    sections: [
      { type: 'paragraph', content: '竞业限制协议', indent: false, style: 'center' },
      { type: 'empty' },
      { type: 'paragraph', content: '甲方（用人单位）：{{公司名称}}', indent: false },
      { type: 'paragraph', content: '统一社会信用代码：{{统一社会信用代码}}', indent: false },
      { type: 'paragraph', content: '地址：{{公司地址}}', indent: false },
      { type: 'paragraph', content: '法定代表人：{{法定代表人}}', indent: false },
      { type: 'paragraph', content: '联系电话：{{公司电话}}', indent: false },
      { type: 'empty' },
      { type: 'paragraph', content: '乙方（劳动者）：{{员工姓名}}', indent: false },
      { type: 'paragraph', content: '身份证号：{{身份证号}}', indent: false },
      { type: 'paragraph', content: '住址：{{员工住址}}', indent: false },
      { type: 'paragraph', content: '联系电话：{{员工电话}}', indent: false },
      { type: 'empty' },
      {
        type: 'paragraph',
        content: '根据《中华人民共和国劳动合同法》及相关法律法规的规定，甲乙双方在平等、自愿的基础上，就竞业限制事宜达成如下协议：'
      },
      { type: 'empty' },
      { type: 'heading', content: '第一条 竞业限制的范围' },
      { type: 'paragraph', content: '1. 竞业限制的地域：{{竞业限制地域}}' },
      { type: 'paragraph', content: '2. 竞业限制的行业：{{竞业限制行业}}' },
      { type: 'paragraph', content: '3. 竞业限制的岗位：{{竞业限制岗位}}' },
      { type: 'paragraph', content: '4. 乙方不得从事以下行为：' },
      { type: 'paragraph', content: '（1）到与甲方生产或者经营同类产品、从事同类业务的有竞争关系的其他用人单位工作；' },
      { type: 'paragraph', content: '（2）自己开业生产或者经营同类产品、从事同类业务；' },
      { type: 'paragraph', content: '（3）为与甲方有竞争关系的其他用人单位提供咨询、顾问等服务；' },
      { type: 'paragraph', content: '（4）{{其他竞业限制行为}}。' },
      { type: 'empty' },
      { type: 'heading', content: '第二条 竞业限制期限' },
      {
        type: 'paragraph',
        content: '竞业限制期限自乙方离职之日起{{期限}}个月，最长不超过{{最长期限}}个月。'
      },
      { type: 'paragraph', content: '竞业限制期限自甲方停止支付竞业限制补偿金之日起终止。' },
      { type: 'empty' },
      { type: 'heading', content: '第三条 竞业限制补偿金' },
      { type: 'paragraph', content: '1. 甲方应向乙方支付竞业限制补偿金，标准为乙方离职前十二个月平均工资的{{比例}}%，即每月人民币{{补偿金金额}}元。' },
      { type: 'paragraph', content: '2. 支付方式：{{支付方式}}' },
      { type: 'paragraph', content: '3. 支付时间：每月{{支付日期}}日前支付上月补偿金。' },
      { type: 'paragraph', content: '4. 支付账户：{{支付账户}}' },
      { type: 'paragraph', content: '5. 如乙方违反本协议约定的，甲方有权停止支付竞业限制补偿金。' },
      { type: 'empty' },
      { type: 'heading', content: '第四条 违约责任' },
      { type: 'paragraph', content: '1. 乙方违反本协议约定的，应当承担以下违约责任：' },
      { type: 'paragraph', content: '（1）立即停止违约行为；' },
      { type: 'paragraph', content: '（2）向甲方支付违约金人民币{{违约金金额}}元；' },
      { type: 'paragraph', content: '（3）赔偿甲方因此遭受的全部损失，包括但不限于直接损失、间接损失、利润损失、商誉损失等；' },
      { type: 'paragraph', content: '（4）将因违约行为获得的收益返还给甲方。' },
      { type: 'paragraph', content: '2. 甲方违反本协议约定，未按时支付竞业限制补偿金的，乙方有权解除本协议。' },
      { type: 'paragraph', content: '3. 甲方连续{{逾期月数}}个月未支付竞业限制补偿金的，视为甲方放弃要求乙方履行竞业限制义务的权利，本协议自动终止。' },
      { type: 'empty' },
      { type: 'heading', content: '第五条 其他约定' },
      { type: 'paragraph', content: '1. 本协议自双方签字之日起生效。' },
      { type: 'paragraph', content: '2. 本协议一式两份，甲乙双方各执一份，具有同等法律效力。' },
      { type: 'paragraph', content: '3. 本协议与劳动合同具有同等法律效力，如与劳动合同有冲突的，以本协议为准。' },
      { type: 'empty' },
      { type: 'paragraph', content: '甲方（盖章）：{{公司名称}}', indent: false },
      { type: 'paragraph', content: '乙方（签字）：{{员工姓名}}', indent: false },
      { type: 'empty' },
      { type: 'paragraph', content: '日期：                            日期：', indent: false }
    ]
  },

  '培训服务协议.docx': {
    title: '培训服务协议',
    category: '劳动人事文书',
    description: '用人单位与劳动者签订的培训服务期协议',
    scene: '员工培训、服务期约定',
    sections: [
      { type: 'paragraph', content: '培训服务协议', indent: false, style: 'center' },
      { type: 'empty' },
      { type: 'paragraph', content: '甲方（用人单位）：{{公司名称}}', indent: false },
      { type: 'paragraph', content: '统一社会信用代码：{{统一社会信用代码}}', indent: false },
      { type: 'paragraph', content: '地址：{{公司地址}}', indent: false },
      { type: 'paragraph', content: '法定代表人：{{法定代表人}}', indent: false },
      { type: 'paragraph', content: '联系电话：{{公司电话}}', indent: false },
      { type: 'empty' },
      { type: 'paragraph', content: '乙方（劳动者）：{{员工姓名}}', indent: false },
      { type: 'paragraph', content: '身份证号：{{身份证号}}', indent: false },
      { type: 'paragraph', content: '住址：{{员工住址}}', indent: false },
      { type: 'paragraph', content: '联系电话：{{员工电话}}', indent: false },
      { type: 'empty' },
      {
        type: 'paragraph',
        content: '根据《中华人民共和国劳动合同法》及相关法律法规的规定，甲乙双方在平等、自愿的基础上，就培训服务期事宜达成如下协议：'
      },
      { type: 'empty' },
      { type: 'heading', content: '第一条 培训内容' },
      { type: 'paragraph', content: '1. 培训项目：{{培训项目}}' },
      { type: 'paragraph', content: '2. 培训内容：{{培训内容}}' },
      { type: 'paragraph', content: '3. 培训方式：{{培训方式}}' },
      { type: 'paragraph', content: '4. 培训地点：{{培训地点}}' },
      { type: 'paragraph', content: '5. 培训时间：自{{开始日期}}起至{{结束日期}}止，共计{{天数}}天。' },
      { type: 'empty' },
      { type: 'heading', content: '第二条 培训费用' },
      { type: 'paragraph', content: '1. 培训费用总额：人民币{{培训费用总额}}元（大写：{{培训费用总额大写}}）' },
      { type: 'paragraph', content: '2. 培训费用包括：{{培训费用明细}}' },
      { type: 'paragraph', content: '3. 培训费用由甲方承担。' },
      { type: 'empty' },
      { type: 'heading', content: '第三条 服务期' },
      {
        type: 'paragraph',
        content: '1. 服务期自培训结束之日起计算，服务期为{{服务期}}年。'
      },
      {
        type: 'paragraph',
        content: '2. 在服务期内，乙方应继续在甲方工作，不得擅自离职。'
      },
      {
        type: 'paragraph',
        content: '3. 服务期届满，乙方可以自由选择是否继续在甲方工作。'
      },
      { type: 'empty' },
      { type: 'heading', content: '第四条 违约责任' },
      { type: 'paragraph', content: '1. 乙方在服务期内擅自离职的，应当承担以下违约责任：' },
      { type: 'paragraph', content: '（1）向甲方支付违约金，违约金的数额不得超过甲方提供的培训费用；' },
      { type: 'paragraph', content: '（2）违约金按照服务期尚未履行部分所应分摊的培训费用计算；' },
      { type: 'paragraph', content: '（3）具体计算公式：违约金 = 培训费用总额 × （未履行服务期 ÷ 约定服务期）' },
      { type: 'paragraph', content: '2. 甲方违反本协议约定，未提供培训或培训不符合约定的，乙方有权解除本协议，并要求甲方赔偿损失。' },
      { type: 'empty' },
      { type: 'heading', content: '第五条 其他约定' },
      { type: 'paragraph', content: '1. 本协议自双方签字之日起生效。' },
      { type: 'paragraph', content: '2. 本协议一式两份，甲乙双方各执一份，具有同等法律效力。' },
      { type: 'paragraph', content: '3. 本协议与劳动合同具有同等法律效力，如与劳动合同有冲突的，以本协议为准。' },
      { type: 'empty' },
      { type: 'paragraph', content: '甲方（盖章）：{{公司名称}}', indent: false },
      { type: 'paragraph', content: '乙方（签字）：{{员工姓名}}', indent: false },
      { type: 'empty' },
      { type: 'paragraph', content: '日期：                            日期：', indent: false }
    ]
  }
}

