// 法律意见书类模板定义
export const 法律意见书模板 = {
  '法律意见书.docx': {
    title: '法律意见书',
    category: '法律意见书',
    description: '律师事务所就特定法律问题出具的专业法律意见',
    scene: '法律咨询与论证',
    sections: [
      { type: 'paragraph', content: '{{律师事务所名称}}法律意见书', indent: false, style: 'center' },
      { type: 'paragraph', content: '（{{年份}}）{{律所简称}}律意字第{{编号}}号', indent: false, style: 'center' },
      { type: 'empty' },
      { type: 'paragraph', content: '致：{{委托人名称}}', indent: false },
      { type: 'paragraph', content: '地址：{{委托人地址}}', indent: false },
      { type: 'paragraph', content: '联系电话：{{委托人电话}}', indent: false },
      { type: 'empty' },
      {
        type: 'paragraph',
        content: '{{律师事务所名称}}（以下简称"本所"）接受{{委托人名称}}（以下简称"委托人"）的委托，指派本所{{律师姓名}}律师（执业证号：{{律师执业证号}}），就{{法律问题}}一事，根据委托人提供的相关材料，依据相关法律法规，出具本法律意见书。'
      },
      { type: 'empty' },
      { type: 'heading', content: '一、出具法律意见书的依据' },
      { type: 'paragraph', content: '1. 委托人提供的以下材料：' },
      { type: 'paragraph', content: '（1）{{材料1名称}}；' },
      { type: 'paragraph', content: '（2）{{材料2名称}}；' },
      { type: 'paragraph', content: '（3）{{材料3名称}}；' },
      { type: 'paragraph', content: '（4）{{材料4名称}}。' },
      { type: 'paragraph', content: '2. 本所律师对相关法律法规的查询和研究。' },
      { type: 'paragraph', content: '3. 本所律师对相关事实的调查和核实。' },
      { type: 'empty' },
      { type: 'heading', content: '二、基本事实' },
      { type: 'paragraph', content: '{{基本事实描述}}' },
      { type: 'paragraph', content: '上述事实有{{证据材料1}}、{{证据材料2}}等材料予以证实。' },
      { type: 'empty' },
      { type: 'heading', content: '三、法律分析' },
      { type: 'heading', content: '（一）适用的法律法规' },
      {
        type: 'paragraph',
        content: '1. 《中华人民共和国民法典》第{{条款}}条："{{法律条文内容}}"。'
      },
      {
        type: 'paragraph',
        content: '2. 《{{相关法律名称}}》第{{条款2}}条："{{法律条文内容2}}"。'
      },
      {
        type: 'paragraph',
        content: '3. 《最高人民法院关于{{相关司法解释名称}}的解释》第{{司法解释条款}}条："{{司法解释内容}}"。'
      },
      { type: 'empty' },
      { type: 'heading', content: '（二）法律分析' },
      { type: 'paragraph', content: '{{法律分析内容}}' },
      { type: 'paragraph', content: '根据上述法律法规的规定，{{分析结论}}。' },
      { type: 'empty' },
      { type: 'heading', content: '四、法律意见' },
      { type: 'paragraph', content: '基于上述事实和法律分析，本所律师认为：' },
      { type: 'paragraph', content: '1. {{法律意见1}}；' },
      { type: 'paragraph', content: '2. {{法律意见2}}；' },
      { type: 'paragraph', content: '3. {{法律意见3}}。' },
      { type: 'empty' },
      { type: 'heading', content: '五、风险提示' },
      { type: 'paragraph', content: '1. {{风险提示1}}；' },
      { type: 'paragraph', content: '2. {{风险提示2}}；' },
      { type: 'paragraph', content: '3. {{风险提示3}}。' },
      { type: 'empty' },
      { type: 'heading', content: '六、特别说明' },
      { type: 'paragraph', content: '1. 本法律意见书仅基于委托人提供的材料及本所律师的调查，如委托人提供的材料不完整或存在虚假，本法律意见书可能不准确。' },
      { type: 'paragraph', content: '2. 本法律意见书仅针对{{法律问题}}，不涉及其他法律问题。' },
      { type: 'paragraph', content: '3. 本法律意见书仅代表本所律师的专业意见，不具有强制执行力。' },
      { type: 'paragraph', content: '4. 本法律意见书仅供委托人参考，委托人应根据实际情况谨慎决策。' },
      { type: 'empty' },
      { type: 'paragraph', content: '特此出具。', indent: false },
      { type: 'empty' },
      { type: 'paragraph', content: '{{律师事务所名称}}（盖章）', indent: false },
      { type: 'paragraph', content: '律师：{{律师姓名}}', indent: false },
      { type: 'paragraph', content: '执业证号：{{执业证号}}', indent: false },
      { type: 'paragraph', content: '联系电话：{{联系电话}}', indent: false },
      { type: 'paragraph', content: '电子邮箱：{{律师邮箱}}', indent: false },
      { type: 'paragraph', content: '地址：{{律所地址}}', indent: false },
      { type: 'empty' },
      { type: 'paragraph', content: '{{日期}}', indent: false }
    ]
  },

  '尽职调查报告.docx': {
    title: '尽职调查报告',
    category: '法律意见书',
    description: '对目标公司或项目进行法律尽职调查后出具的专业报告',
    scene: '投资并购、项目评估',
    sections: [
      { type: 'paragraph', content: '{{律师事务所名称}}尽职调查报告', indent: false, style: 'center' },
      { type: 'paragraph', content: '（{{年份}}）{{律所简称}}律尽调字第{{编号}}号', indent: false, style: 'center' },
      { type: 'empty' },
      { type: 'paragraph', content: '致：{{委托人名称}}', indent: false },
      { type: 'paragraph', content: '地址：{{委托人地址}}', indent: false },
      { type: 'paragraph', content: '联系电话：{{委托人电话}}', indent: false },
      { type: 'empty' },
      {
        type: 'paragraph',
        content: '{{律师事务所名称}}（以下简称"本所"）接受{{委托人名称}}（以下简称"委托人"）的委托，对{{目标公司/项目名称}}（以下简称"目标公司"）进行法律尽职调查。本所律师根据相关法律法规，对目标公司进行了全面调查，现出具本尽职调查报告。'
      },
      { type: 'empty' },
      { type: 'heading', content: '一、调查范围与方法' },
      { type: 'paragraph', content: '1. 调查范围：' },
      { type: 'paragraph', content: '（1）目标公司的基本情况；' },
      { type: 'paragraph', content: '（2）目标公司的股权结构；' },
      { type: 'paragraph', content: '（3）目标公司的资产状况；' },
      { type: 'paragraph', content: '（4）目标公司的重大合同；' },
      { type: 'paragraph', content: '（5）目标公司的知识产权；' },
      { type: 'paragraph', content: '（6）目标公司的劳动人事；' },
      { type: 'paragraph', content: '（7）目标公司的诉讼、仲裁及行政处罚；' },
      { type: 'paragraph', content: '（8）{{其他调查事项}}。' },
      { type: 'paragraph', content: '2. 调查方法：' },
      { type: 'paragraph', content: '（1）审阅目标公司提供的文件资料；' },
      { type: 'paragraph', content: '（2）查询相关政府部门公开信息；' },
      { type: 'paragraph', content: '（3）对目标公司进行实地调查；' },
      { type: 'paragraph', content: '（4）对相关人员进行访谈。' },
      { type: 'empty' },
      { type: 'heading', content: '二、目标公司基本情况' },
      { type: 'paragraph', content: '1. 公司名称：{{公司名称}}' },
      { type: 'paragraph', content: '2. 统一社会信用代码：{{统一社会信用代码}}' },
      { type: 'paragraph', content: '3. 注册地址：{{注册地址}}' },
      { type: 'paragraph', content: '4. 法定代表人：{{法定代表人}}' },
      { type: 'paragraph', content: '5. 注册资本：人民币{{注册资本}}元' },
      { type: 'paragraph', content: '6. 成立日期：{{成立日期}}' },
      { type: 'paragraph', content: '7. 经营范围：{{经营范围}}' },
      { type: 'empty' },
      { type: 'heading', content: '三、股权结构' },
      { type: 'paragraph', content: '{{股权结构说明}}' },
      { type: 'paragraph', content: '经调查，目标公司的股权结构如下：' },
      { type: 'paragraph', content: '1. {{股东1名称}}：持股{{持股比例}}%，认缴出资{{认缴出资}}元，实缴出资{{实缴出资}}元；' },
      { type: 'paragraph', content: '2. {{股东2名称}}：持股{{持股比例}}%，认缴出资{{认缴出资}}元，实缴出资{{实缴出资}}元；' },
      { type: 'paragraph', content: '3. {{股东3名称}}：持股{{持股比例}}%，认缴出资{{认缴出资}}元，实缴出资{{实缴出资}}元。' },
      { type: 'empty' },
      { type: 'heading', content: '四、资产状况' },
      { type: 'paragraph', content: '1. 固定资产：{{固定资产说明}}' },
      { type: 'paragraph', content: '2. 无形资产：{{无形资产说明}}' },
      { type: 'paragraph', content: '3. 对外投资：{{对外投资说明}}' },
      { type: 'paragraph', content: '4. 主要资产：{{主要资产说明}}' },
      { type: 'empty' },
      { type: 'heading', content: '五、重大合同' },
      { type: 'paragraph', content: '经调查，目标公司的主要合同包括：' },
      { type: 'paragraph', content: '1. {{合同1名称}}（合同编号：{{合同编号}}，合同金额：{{合同金额}}元）；' },
      { type: 'paragraph', content: '2. {{合同2名称}}（合同编号：{{合同编号}}，合同金额：{{合同金额}}元）；' },
      { type: 'paragraph', content: '3. {{合同3名称}}（合同编号：{{合同编号}}，合同金额：{{合同金额}}元）。' },
      { type: 'paragraph', content: '{{重大合同风险说明}}' },
      { type: 'empty' },
      { type: 'heading', content: '六、知识产权' },
      { type: 'paragraph', content: '1. 商标：{{商标情况}}' },
      { type: 'paragraph', content: '2. 专利：{{专利情况}}' },
      { type: 'paragraph', content: '3. 著作权：{{著作权情况}}' },
      { type: 'paragraph', content: '4. 商业秘密：{{商业秘密情况}}' },
      { type: 'paragraph', content: '{{知识产权风险说明}}' },
      { type: 'empty' },
      { type: 'heading', content: '七、劳动人事' },
      { type: 'paragraph', content: '1. 员工总数：{{员工总数}}人' },
      { type: 'paragraph', content: '2. 劳动合同签订情况：{{劳动合同签订情况}}' },
      { type: 'paragraph', content: '3. 社会保险缴纳情况：{{社会保险缴纳情况}}' },
      { type: 'paragraph', content: '4. 劳动争议情况：{{劳动争议情况}}' },
      { type: 'paragraph', content: '{{劳动人事风险说明}}' },
      { type: 'empty' },
      { type: 'heading', content: '八、诉讼、仲裁及行政处罚' },
      { type: 'paragraph', content: '1. 诉讼案件：{{诉讼案件说明}}' },
      { type: 'paragraph', content: '2. 仲裁案件：{{仲裁案件说明}}' },
      { type: 'paragraph', content: '3. 行政处罚：{{行政处罚说明}}' },
      { type: 'paragraph', content: '{{法律风险说明}}' },
      { type: 'empty' },
      { type: 'heading', content: '九、主要法律风险' },
      { type: 'paragraph', content: '1. {{法律风险1}}；' },
      { type: 'paragraph', content: '2. {{法律风险2}}；' },
      { type: 'paragraph', content: '3. {{法律风险3}}；' },
      { type: 'paragraph', content: '4. {{法律风险4}}。' },
      { type: 'empty' },
      { type: 'heading', content: '十、结论与建议' },
      { type: 'paragraph', content: '基于上述调查，本所律师认为：' },
      { type: 'paragraph', content: '1. {{结论1}}；' },
      { type: 'paragraph', content: '2. {{结论2}}；' },
      { type: 'paragraph', content: '3. {{建议1}}；' },
      { type: 'paragraph', content: '4. {{建议2}}。' },
      { type: 'empty' },
      { type: 'heading', content: '十一、特别说明' },
      { type: 'paragraph', content: '1. 本报告仅基于目标公司提供的材料及本所律师的调查，如目标公司提供的材料不完整或存在虚假，本报告可能不准确。' },
      { type: 'paragraph', content: '2. 本报告仅针对法律尽职调查，不涉及财务、税务等其他方面的尽职调查。' },
      { type: 'paragraph', content: '3. 本报告仅供委托人参考，委托人应根据实际情况谨慎决策。' },
      { type: 'empty' },
      { type: 'paragraph', content: '特此报告。', indent: false },
      { type: 'empty' },
      { type: 'paragraph', content: '{{律师事务所名称}}（盖章）', indent: false },
      { type: 'paragraph', content: '律师：{{律师姓名}}', indent: false },
      { type: 'paragraph', content: '执业证号：{{执业证号}}', indent: false },
      { type: 'paragraph', content: '联系电话：{{联系电话}}', indent: false },
      { type: 'paragraph', content: '电子邮箱：{{律师邮箱}}', indent: false },
      { type: 'paragraph', content: '地址：{{律所地址}}', indent: false },
      { type: 'empty' },
      { type: 'paragraph', content: '{{日期}}', indent: false }
    ]
  }
}

