// 知识产权文书类模板定义
export const 知识产权文书模板 = {
  '商标使用许可合同.docx': {
    title: '商标使用许可合同',
    category: '知识产权文书',
    description: '商标权人许可他人使用其注册商标的合同',
    scene: '商标许可使用',
    sections: [
      { type: 'paragraph', content: '商标使用许可合同', indent: false, style: 'center' },
      { type: 'empty' },
      { type: 'paragraph', content: '许可方（甲方）：{{许可方名称}}', indent: false },
      { type: 'paragraph', content: '统一社会信用代码：{{许可方统一社会信用代码}}', indent: false },
      { type: 'paragraph', content: '地址：{{许可方地址}}', indent: false },
      { type: 'paragraph', content: '法定代表人：{{许可方法定代表人}}', indent: false },
      { type: 'paragraph', content: '联系电话：{{许可方电话}}', indent: false },
      { type: 'empty' },
      { type: 'paragraph', content: '被许可方（乙方）：{{被许可方名称}}', indent: false },
      { type: 'paragraph', content: '统一社会信用代码：{{被许可方统一社会信用代码}}', indent: false },
      { type: 'paragraph', content: '地址：{{被许可方地址}}', indent: false },
      { type: 'paragraph', content: '法定代表人：{{被许可方法定代表人}}', indent: false },
      { type: 'paragraph', content: '联系电话：{{被许可方电话}}', indent: false },
      { type: 'empty' },
      {
        type: 'paragraph',
        content: '根据《中华人民共和国商标法》及相关法律法规的规定，甲乙双方在平等、自愿的基础上，就商标使用许可事宜达成如下协议：'
      },
      { type: 'empty' },
      { type: 'heading', content: '第一条 许可使用的商标' },
      { type: 'paragraph', content: '1. 商标名称：{{商标名称}}' },
      { type: 'paragraph', content: '2. 商标注册号：{{商标注册号}}' },
      { type: 'paragraph', content: '3. 商标类别：第{{类别}}类' },
      { type: 'paragraph', content: '4. 商标图样：{{商标图样说明}}' },
      { type: 'paragraph', content: '5. 甲方保证对上述商标享有合法的注册商标专用权。' },
      { type: 'empty' },
      { type: 'heading', content: '第二条 许可使用的方式' },
      { type: 'paragraph', content: '1. 许可使用方式：{{许可使用方式}}（独占许可/排他许可/普通许可）' },
      { type: 'paragraph', content: '2. 许可使用范围：{{许可使用范围}}' },
      { type: 'paragraph', content: '3. 许可使用地域：{{许可使用地域}}' },
      { type: 'paragraph', content: '4. 许可使用商品或服务：{{许可使用商品或服务}}' },
      { type: 'empty' },
      { type: 'heading', content: '第三条 许可使用期限' },
      {
        type: 'paragraph',
        content: '许可使用期限自{{开始日期}}起至{{结束日期}}止，共计{{期限}}年。'
      },
      { type: 'paragraph', content: '许可使用期限届满，如双方需继续合作的，应另行签订许可合同。' },
      { type: 'empty' },
      { type: 'heading', content: '第四条 许可使用费' },
      { type: 'paragraph', content: '1. 许可使用费总额：人民币{{许可使用费总额}}元（大写：{{许可使用费总额大写}}）' },
      { type: 'paragraph', content: '2. 支付方式：{{支付方式}}' },
      { type: 'paragraph', content: '3. 支付时间：{{支付时间}}' },
      { type: 'paragraph', content: '4. 支付账户：{{支付账户}}' },
      { type: 'empty' },
      { type: 'heading', content: '第五条 双方权利义务' },
      { type: 'paragraph', content: '（一）甲方的权利义务：' },
      { type: 'paragraph', content: '1. 甲方有权监督乙方使用许可商标的商品或服务质量；' },
      { type: 'paragraph', content: '2. 甲方有权要求乙方在使用许可商标的商品上标明被许可人的名称和商品产地；' },
      { type: 'paragraph', content: '3. 甲方应保证许可商标的合法性和有效性；' },
      { type: 'paragraph', content: '4. 甲方不得在许可使用期限内将许可商标再许可给第三方（普通许可除外）。' },
      { type: 'paragraph', content: '（二）乙方的权利义务：' },
      { type: 'paragraph', content: '1. 乙方有权在许可范围内使用许可商标；' },
      { type: 'paragraph', content: '2. 乙方应保证使用许可商标的商品或服务质量符合相关标准；' },
      { type: 'paragraph', content: '3. 乙方应在使用许可商标的商品上标明被许可人的名称和商品产地；' },
      { type: 'paragraph', content: '4. 乙方不得超出许可范围使用许可商标；' },
      { type: 'paragraph', content: '5. 乙方不得将许可商标再许可给第三方。' },
      { type: 'empty' },
      { type: 'heading', content: '第六条 违约责任' },
      { type: 'paragraph', content: '1. 甲方违反本协议约定，导致许可商标被撤销或无效的，应退还已收取的许可使用费，并赔偿乙方因此遭受的全部损失。' },
      { type: 'paragraph', content: '2. 乙方违反本协议约定，超出许可范围使用许可商标的，应支付违约金人民币{{违约金金额}}元，并赔偿甲方因此遭受的全部损失。' },
      { type: 'paragraph', content: '3. 乙方逾期支付许可使用费的，每逾期一日，按应付金额的{{逾期违约金比例}}%（日利率）支付违约金。' },
      { type: 'empty' },
      { type: 'heading', content: '第七条 合同解除' },
      { type: 'paragraph', content: '1. 有下列情形之一的，甲方有权解除本合同：' },
      { type: 'paragraph', content: '（1）乙方超出许可范围使用许可商标，经甲方通知后拒不改正的；' },
      { type: 'paragraph', content: '（2）乙方使用许可商标的商品或服务质量不符合相关标准，经甲方通知后拒不改正的；' },
      { type: 'paragraph', content: '（3）乙方逾期支付许可使用费超过{{逾期天数}}日的。' },
      { type: 'paragraph', content: '2. 有下列情形之一的，乙方有权解除本合同：' },
      { type: 'paragraph', content: '（1）许可商标被撤销或无效的；' },
      { type: 'paragraph', content: '（2）甲方违反本协议约定，将许可商标再许可给第三方的。' },
      { type: 'empty' },
      { type: 'heading', content: '第八条 争议解决' },
      {
        type: 'paragraph',
        content: '本合同履行过程中发生争议的，由双方协商解决；协商不成的，依法向{{管辖法院}}人民法院起诉。'
      },
      { type: 'empty' },
      { type: 'heading', content: '第九条 其他约定' },
      { type: 'paragraph', content: '1. 本合同自双方签字（盖章）之日起生效。' },
      { type: 'paragraph', content: '2. 本合同一式{{份数}}份，甲乙双方各执一份，具有同等法律效力。' },
      { type: 'paragraph', content: '3. 本合同未尽事宜，由双方协商解决。' },
      { type: 'empty' },
      { type: 'paragraph', content: '甲方（盖章）：{{许可方名称}}', indent: false },
      { type: 'paragraph', content: '乙方（盖章）：{{被许可方名称}}', indent: false },
      { type: 'empty' },
      { type: 'paragraph', content: '法定代表人（签字）：            法定代表人（签字）：', indent: false },
      { type: 'empty' },
      { type: 'paragraph', content: '日期：                            日期：', indent: false }
    ]
  },

  '专利实施许可合同.docx': {
    title: '专利实施许可合同',
    category: '知识产权文书',
    description: '专利权人许可他人实施其专利的合同',
    scene: '专利许可使用',
    sections: [
      { type: 'paragraph', content: '专利实施许可合同', indent: false, style: 'center' },
      { type: 'empty' },
      { type: 'paragraph', content: '许可方（甲方）：{{许可方名称}}', indent: false },
      { type: 'paragraph', content: '统一社会信用代码：{{许可方统一社会信用代码}}', indent: false },
      { type: 'paragraph', content: '地址：{{许可方地址}}', indent: false },
      { type: 'paragraph', content: '法定代表人：{{许可方法定代表人}}', indent: false },
      { type: 'paragraph', content: '联系电话：{{许可方电话}}', indent: false },
      { type: 'empty' },
      { type: 'paragraph', content: '被许可方（乙方）：{{被许可方名称}}', indent: false },
      { type: 'paragraph', content: '统一社会信用代码：{{被许可方统一社会信用代码}}', indent: false },
      { type: 'paragraph', content: '地址：{{被许可方地址}}', indent: false },
      { type: 'paragraph', content: '法定代表人：{{被许可方法定代表人}}', indent: false },
      { type: 'paragraph', content: '联系电话：{{被许可方电话}}', indent: false },
      { type: 'empty' },
      {
        type: 'paragraph',
        content: '根据《中华人民共和国专利法》及相关法律法规的规定，甲乙双方在平等、自愿的基础上，就专利实施许可事宜达成如下协议：'
      },
      { type: 'empty' },
      { type: 'heading', content: '第一条 许可实施的专利' },
      { type: 'paragraph', content: '1. 专利名称：{{专利名称}}' },
      { type: 'paragraph', content: '2. 专利号：{{专利号}}' },
      { type: 'paragraph', content: '3. 专利类型：{{专利类型}}（发明专利/实用新型专利/外观设计专利）' },
      { type: 'paragraph', content: '4. 专利申请日：{{专利申请日}}' },
      { type: 'paragraph', content: '5. 专利授权日：{{专利授权日}}' },
      { type: 'paragraph', content: '6. 专利权人：{{专利权人}}' },
      { type: 'paragraph', content: '7. 甲方保证对上述专利享有合法的专利权。' },
      { type: 'empty' },
      { type: 'heading', content: '第二条 许可实施的方式' },
      { type: 'paragraph', content: '1. 许可实施方式：{{许可实施方式}}（独占许可/排他许可/普通许可）' },
      { type: 'paragraph', content: '2. 许可实施范围：{{许可实施范围}}' },
      { type: 'paragraph', content: '3. 许可实施地域：{{许可实施地域}}' },
      { type: 'empty' },
      { type: 'heading', content: '第三条 许可实施期限' },
      {
        type: 'paragraph',
        content: '许可实施期限自{{开始日期}}起至{{结束日期}}止，或至专利有效期届满之日止。'
      },
      { type: 'empty' },
      { type: 'heading', content: '第四条 许可使用费' },
      { type: 'paragraph', content: '1. 许可使用费总额：人民币{{许可使用费总额}}元（大写：{{许可使用费总额大写}}）' },
      { type: 'paragraph', content: '2. 支付方式：{{支付方式}}' },
      { type: 'paragraph', content: '3. 支付时间：{{支付时间}}' },
      { type: 'paragraph', content: '4. 支付账户：{{支付账户}}' },
      { type: 'empty' },
      { type: 'heading', content: '第五条 技术资料交付' },
      { type: 'paragraph', content: '1. 甲方应在{{交付期限}}日内向乙方交付以下技术资料：' },
      { type: 'paragraph', content: '（1）{{技术资料1}}；' },
      { type: 'paragraph', content: '（2）{{技术资料2}}；' },
      { type: 'paragraph', content: '（3）{{技术资料3}}。' },
      { type: 'paragraph', content: '2. 甲方应提供技术指导，协助乙方实施专利。' },
      { type: 'empty' },
      { type: 'heading', content: '第六条 双方权利义务' },
      { type: 'paragraph', content: '（一）甲方的权利义务：' },
      { type: 'paragraph', content: '1. 甲方有权监督乙方实施专利的情况；' },
      { type: 'paragraph', content: '2. 甲方应保证专利的合法性和有效性；' },
      { type: 'paragraph', content: '3. 甲方应提供必要的技术指导。' },
      { type: 'paragraph', content: '（二）乙方的权利义务：' },
      { type: 'paragraph', content: '1. 乙方有权在许可范围内实施专利；' },
      { type: 'paragraph', content: '2. 乙方应按照约定的方式实施专利；' },
      { type: 'paragraph', content: '3. 乙方不得超出许可范围实施专利；' },
      { type: 'paragraph', content: '4. 乙方不得将专利再许可给第三方。' },
      { type: 'empty' },
      { type: 'heading', content: '第七条 违约责任' },
      { type: 'paragraph', content: '1. 甲方违反本协议约定，导致专利被宣告无效的，应退还已收取的许可使用费，并赔偿乙方因此遭受的全部损失。' },
      { type: 'paragraph', content: '2. 乙方违反本协议约定，超出许可范围实施专利的，应支付违约金人民币{{违约金金额}}元，并赔偿甲方因此遭受的全部损失。' },
      { type: 'paragraph', content: '3. 乙方逾期支付许可使用费的，每逾期一日，按应付金额的{{逾期违约金比例}}%（日利率）支付违约金。' },
      { type: 'empty' },
      { type: 'heading', content: '第八条 争议解决' },
      {
        type: 'paragraph',
        content: '本合同履行过程中发生争议的，由双方协商解决；协商不成的，依法向{{管辖法院}}人民法院起诉。'
      },
      { type: 'empty' },
      { type: 'heading', content: '第九条 其他约定' },
      { type: 'paragraph', content: '1. 本合同自双方签字（盖章）之日起生效。' },
      { type: 'paragraph', content: '2. 本合同一式{{份数}}份，甲乙双方各执一份，具有同等法律效力。' },
      { type: 'empty' },
      { type: 'paragraph', content: '甲方（盖章）：{{许可方名称}}', indent: false },
      { type: 'paragraph', content: '乙方（盖章）：{{被许可方名称}}', indent: false },
      { type: 'empty' },
      { type: 'paragraph', content: '法定代表人（签字）：            法定代表人（签字）：', indent: false },
      { type: 'empty' },
      { type: 'paragraph', content: '日期：                            日期：', indent: false }
    ]
  }
}

